### PR TITLE
primal-sieve: Avoid UB use of `pointer::offset`

### LINKED ISSUE #35: Strange Miri error with pointer offset out of bounds in primal-sieve
I've been running `cargo miri test` on a lot of crates. Usually when Miri says it has found undefined behavior I can at least get some idea of what's going on, but I'm really stumped on this one.

I ran `cargo miri test` on `primal-estimate` on the latest commit (Miri is very slow, so whether the `primal-sieve` test suite detects this I don't have the patience to wait for it at the moment). I get an error that says:
```
   --> /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/ptr/mut_ptr.rs:307:18
    |
307 |         unsafe { intrinsics::offset(self, count) as *mut T }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ pointer arithmetic failed: alloc117012 has size 32768, so pointer to 3 bytes starting at offset 32766 is out-of-bounds
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
            
    = note: inside `std::ptr::mut_ptr::<impl *mut u8>::offset` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/ptr/mut_ptr.rs:307:18
    = note: inside `primal_sieve::wheel::wheel30::hardcoded_sieve` at /tmp/primal/primal-sieve/src/wheel/wheel30.rs:822:31
    = note: inside `<primal_sieve::wheel::wheel30::Wheel30 as primal_sieve::wheel::Wheel>::hardcoded_sieve` at /tmp/primal/primal-sieve/src/wheel/wheel30.rs:23:9
    = note: inside `primal_sieve::wheel::State::<primal_sieve::wheel::wheel30::Wheel30>::sieve_hardcoded` at /tmp/primal/primal-sieve/src/wheel/mod.rs:210:13
    = note: inside `primal::StreamingSieve::small_primes_sieve::<primal_sieve::wheel::wheel30::Wheel30>` at /tmp/primal/primal-sieve/src/streaming/mod.rs:200:13
    = note: inside `primal::StreamingSieve::next` at /tmp/primal/primal-sieve/src/streaming/mod.rs:251:9
    = note: inside `primal::Sieve::new` at /tmp/primal/primal-sieve/src/sieve.rs:69:45
note: inside `tests::nth_prime` at primal-estimate/src/lib.rs:212:21
   --> primal-estimate/src/lib.rs:212:21
    |
212 |         let sieve = Sieve::new(1_000_000);
    |                     ^^^^^^^^^^^^^^^^^^^^^

```
What really confuses me is the `pointer to 3 bytes`. As far as I can tell the pointer in use here is a `*const u8`. But this error seems to suggest that it's a `*const [u8; 3]`. I'm probably just getting lost in the implementation of `hardcoded_sieve`.

If this Miri error is correct, I think this is UB. Rust permits computing the one-past-the-end pointer, but not dereferencing it. But I think the error message says the pointer is straddling the end of the array, so it doesn't qualify as a one-past-the-end pointer, even though its pointee extends one byte past the end of what I think is an array of `u8`.

I don't think there is a _dereference_ of a pointer at an invalid offset. The test suite passes with Address Sanitizer.

If this is confusing to you as well, do you think there is anything Miri could say that would make this easier to understand?

### PR DESCRIPTION
**Pull request by cuviper**
We must not use `pointer::offset` when the result may be out of bounds.

- In the `safe_assert!` checks, use `wrapping_offset`. We're comparing
  to both start and end pointers, so it can handle overflowing the end or even
  wrapping around less than start.
- For other updates, use `wrapping_offset` and assign `end` if it did wrap,
  so further code only has to check it against the end pointer.

Fixes #35.

I've also included a few minor updates and a release bump:

- Use panic formatting in a test to avoid a deprecation
- Release primal-sieve 0.3.2
- Migrate from criterion deprecations

### CODE REVIEW

File: generators/src/bin/wheel-generator.rs [hunk 1]
```diff
@@ -273,7 +273,7 @@ pub unsafe fn hardcoded_sieve(bytes: &mut [u8], si_: &mut usize, wi_: &mut usize
                      bit = info.unset_bit, indent = indent);
         }
         println!("
-{indent}    p = p.offset(prime_ * {} + {})
+{indent}    p = (p as usize).saturating_add(prime * {} + {}) as *mut u8;
```
Comment (saethlin) [inline generators/src/bin/wheel-generator.rs:276]: Why are we converting to `usize` here? What's wrong with `wrapping_offset`?

Comment (cuviper) [reply generators/src/bin/wheel-generator.rs:276]: I'm feeling paranoid that the pointer may actually **wrap**, such that `p < end` is still true while being wildly out of bounds. We could let it wrap and also check `p >= start`, but I found that performed worse than this `saturating_add`.

In practice, wrapping is improbable because the kernel usually owns the entire upper address space. But IIRC, a 32-bit process on a 64-bit kernel is allowed to use almost all of its 4GB 32-bit address space, so it might get close. I suppose `primal` could be used in a kernel or embedded environment too, if you're adventurous. :)

Comment (saethlin) [reply generators/src/bin/wheel-generator.rs:276]: Ah, I see.

The potential problem with round-tripping through a `usize` is that currently it confuses Miri (you're actually told that the code is UB), and it's not clear if this code as-written will ever "just work" under Stacked Borrows. The crux of the problem is that it's not clear what the provenance is of the pointer that comes out of that int-to-pointer cast. There are ideas on how to solve this, but that's a bit besides the point. If you use this implementation, you can only run Miri with `-Zmiri-disable-stacked-borrows`. That might be okay for you. I think the issue that prompted this change would still be uncovered with that flag, because the issue is actually reported by the rustc const eval machinery.

Normally here is where I would suggest some alternative but pointers are the darnedest things. So if you want to keep this saturating check I'd just like to see a comment that tries to explain why there's this whole dance going on.

Comment (cuviper) [reply generators/src/bin/wheel-generator.rs:276]: Hmm, I ran with `cargo +nightly miri test` and did not see any warnings or errors. Can you share how "confuse" Miri with this?

I could also try manual saturation, something like:

```rust
let p2 = p.wrapping_offset(...);
p = if p < p2 { p2 } else { end };
```

If LLVM realized that this `p < p2` corresponds to the overflow flag, this might have about the same cost as `saturating_add`.

Comment (saethlin) [reply generators/src/bin/wheel-generator.rs:276]: You need to set `MIRIFLAGS="-Zmiri-tag-raw-pointers"`. By default it implements an incomplete form of Stacked Borrows, and I never did get around to asking Ralf why.
