### PR TITLE
Big refactoring

### LINKED ISSUE #10: primal fails on big-endian machines
I found that primal generates incorrect results on powerp64-unknown-linux-gnu, which is big endian.  A lot of tests fail, but I think it can be traced to primal-bit's storage.  That uses a `Vec<u64>` which is in some cases directly cast to byte slices, without considering endianness.

```
---- tests::find_nth_bit stdout ----
        thread 'tests::find_nth_bit' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(4992)`', src/lib.rs:423
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- tests::count_ones_before stdout ----
        thread 'tests::count_ones_before' panicked at 'assertion failed: `(left == right)`
  left: `9984`,
 right: `9985`', src/lib.rs:407
```

### PR DESCRIPTION
**Pull request by cuviper**
Sorry for a mega-PR, but I've been tinkering with upgrading dependencies
and fixing the big-endian problems. In trying to recoup performance, all
of these changes got intertwined. At a high level:

- Bump all crates to 0.3 to account for breaking changes.
- Upgrade to smallvec 1 -- raises the minimum Rust to 1.36.
- Various dev-dependencies are upgraded as well.
- `primal_bit::BitVec` now stores a `Vec<u8>`, and no longer exposes
  methods that depend on endianness. Fixes #10.
  - A lot of the wheel operations were byte-oriented already, so they
    really depended on little-endian order before. With `Vec<u8>`, even
    big-endian targets have the expected byte order to find bits.
- Iterators specialize methods like `fold` and `all` for performance.

We should probably update to 2018 edition too, but I didn't bother yet.

### CODE REVIEW

**Comment by autohuonw** [comment]
r? @huonw

(rust_highfive has picked a reviewer for you, use r? to override)

**Comment by cuviper** [comment]
I used [critcmp](https://crates.io/crates/critcmp) to compare criterion results with the master branch. It's a little weird in that instead of just calculating from old to new, it holds the fastest one as 1.00 on each benchmark (in bold green, but the color's not showing here), and reports the ratio >1 for the other.

<details> 
  <summary><code>primal</code> benchmarks</summary>
<pre>group                                 master                                 refactor
-----                                 ------                                 --------
is_prime/Sieve::is_prime              1.29     42.8±1.06µs        ? B/sec<font color="#859900"><b>    1.00     33.3±0.68µs        ? B/sec</b></font>
is_prime/Sieve::is_prime with init    1.08    174.3±1.62µs        ? B/sec<font color="#859900"><b>    1.00    160.9±0.22µs        ? B/sec</b></font>
is_prime/is_prime<font color="#859900"><b>                     1.00    640.3±0.82µs        ? B/sec</b></font>    1.00    643.0±4.22µs        ? B/sec
</pre>
</details>

<details> 
  <summary><code>primal-sieve</code> benchmarks</summary>
<pre>group                                master                                 refactor
-----                                ------                                 --------
factor/Sieve/1048573                 1.02    792.2±3.80ns        ? B/sec<font color="#859900"><b>    1.00    777.2±1.62ns        ? B/sec</b></font>
factor/Sieve/131                     1.09     42.3±1.26ns        ? B/sec<font color="#859900"><b>    1.00     38.9±0.22ns        ? B/sec</b></font>
factor/Sieve/65521                   1.02    249.3±2.89ns        ? B/sec<font color="#859900"><b>    1.00    245.4±0.54ns        ? B/sec</b></font>
factor/Sieve/7561                    1.05    114.0±1.70ns        ? B/sec<font color="#859900"><b>    1.00    108.8±0.46ns        ? B/sec</b></font>
factor/Sieve/9699690                 1.44    133.5±1.54ns        ? B/sec<font color="#859900"><b>    1.00     92.8±0.64ns        ? B/sec</b></font>
iterate/Primes/100                   1.01    135.1±0.45µs        ? B/sec<font color="#859900"><b>    1.00    133.1±0.07µs        ? B/sec</b></font>
iterate/Primes/10000                 1.02    140.1±3.22µs        ? B/sec<font color="#859900"><b>    1.00    137.4±0.07µs        ? B/sec</b></font>
iterate/Primes/100000<font color="#859900"><b>                1.00    165.5±1.05µs        ? B/sec</b></font>    1.02    168.5±0.44µs        ? B/sec
iterate/Primes/1000000<font color="#859900"><b>               1.00    481.4±3.70µs        ? B/sec</b></font>    1.03    495.1±2.40µs        ? B/sec
iterate/Primes/10000000<font color="#859900"><b>              1.00      3.2±0.04ms        ? B/sec</b></font>    1.07      3.5±0.02ms        ? B/sec
iterate/Sieve with init/100          1.29    123.0±1.32ns        ? B/sec<font color="#859900"><b>    1.00     95.6±0.61ns        ? B/sec</b></font>
iterate/Sieve with init/10000        1.73      3.8±0.02µs        ? B/sec<font color="#859900"><b>    1.00      2.2±0.02µs        ? B/sec</b></font>
iterate/Sieve with init/100000       1.49     35.8±0.28µs        ? B/sec<font color="#859900"><b>    1.00     24.0±0.09µs        ? B/sec</b></font>
iterate/Sieve with init/1000000      1.36    385.5±1.93µs        ? B/sec<font color="#859900"><b>    1.00    283.4±2.05µs        ? B/sec</b></font>
iterate/Sieve with init/10000000     1.34      3.0±0.04ms        ? B/sec<font color="#859900"><b>    1.00      2.2±0.00ms        ? B/sec</b></font>
iterate/Sieve/100                    1.66     89.7±1.66ns        ? B/sec<font color="#859900"><b>    1.00     54.1±0.14ns        ? B/sec</b></font>
iterate/Sieve/10000                  1.83      3.7±0.05µs        ? B/sec<font color="#859900"><b>    1.00      2.0±0.01µs        ? B/sec</b></font>
iterate/Sieve/100000                 1.76     30.1±0.33µs        ? B/sec<font color="#859900"><b>    1.00     17.2±0.04µs        ? B/sec</b></font>
iterate/Sieve/1000000                1.64    248.1±2.26µs        ? B/sec<font color="#859900"><b>    1.00    151.0±1.02µs        ? B/sec</b></font>
iterate/Sieve/10000000               1.58      2.1±0.02ms        ? B/sec<font color="#859900"><b>    1.00   1342.1±6.61µs        ? B/sec</b></font>
new/Sieve/100                        1.03     38.6±1.49ns        ? B/sec<font color="#859900"><b>    1.00     37.5±0.24ns        ? B/sec</b></font>
new/Sieve/10000                      1.01    131.4±0.36ns        ? B/sec<font color="#859900"><b>    1.00    130.2±2.60ns        ? B/sec</b></font>
new/Sieve/100000<font color="#859900"><b>                     1.00      6.3±0.01µs        ? B/sec</b></font>    1.02      6.5±0.04µs        ? B/sec
new/Sieve/1000000<font color="#859900"><b>                    1.00    129.1±0.72µs        ? B/sec</b></font>    1.01    130.3±1.03µs        ? B/sec
new/Sieve/10000000                   1.01    860.6±6.44µs        ? B/sec<font color="#859900"><b>    1.00    851.2±4.66µs        ? B/sec</b></font>
nth_prime/Primes/100                 1.01    134.8±0.67µs        ? B/sec<font color="#859900"><b>    1.00    134.0±0.88µs        ? B/sec</b></font>
nth_prime/Primes/10000<font color="#859900"><b>               1.00    166.9±1.28µs        ? B/sec</b></font>    1.04    172.9±0.60µs        ? B/sec
nth_prime/Primes/100000<font color="#859900"><b>              1.00    554.8±4.39µs        ? B/sec</b></font>    1.05    581.2±1.97µs        ? B/sec
nth_prime/Primes/1000000<font color="#859900"><b>             1.00      4.8±0.05ms        ? B/sec</b></font>    1.07      5.2±0.02ms        ? B/sec
nth_prime/Sieve with init/100<font color="#859900"><b>        1.00    110.0±1.16ns        ? B/sec</b></font>    1.04    114.2±0.75ns        ? B/sec
nth_prime/Sieve with init/10000      1.01      7.8±0.23µs        ? B/sec<font color="#859900"><b>    1.00      7.7±0.02µs        ? B/sec</b></font>
nth_prime/Sieve with init/100000     1.02    134.5±4.45µs        ? B/sec<font color="#859900"><b>    1.00    132.3±0.19µs        ? B/sec</b></font>
nth_prime/Sieve with init/1000000<font color="#859900"><b>    1.00  1279.1±44.83µs        ? B/sec</b></font>    1.00   1283.7±3.81µs        ? B/sec
nth_prime/Sieve/100                  1.03     28.8±0.27ns        ? B/sec<font color="#859900"><b>    1.00     27.9±0.25ns        ? B/sec</b></font>
nth_prime/Sieve/10000<font color="#859900"><b>                1.00    873.9±5.57ns        ? B/sec</b></font>    1.01    884.9±2.75ns        ? B/sec
nth_prime/Sieve/100000<font color="#859900"><b>               1.00      2.1±0.02µs        ? B/sec</b></font>    1.02      2.1±0.01µs        ? B/sec
nth_prime/Sieve/1000000<font color="#859900"><b>              1.00      2.2±0.01µs        ? B/sec</b></font>    1.01      2.2±0.02µs        ? B/sec
nth_prime/StreamingSieve/100         1.01    359.4±3.39ns        ? B/sec<font color="#859900"><b>    1.00    355.1±1.31ns        ? B/sec</b></font>
nth_prime/StreamingSieve/10000       1.00      7.6±0.04µs        ? B/sec<font color="#859900"><b>    1.00      7.6±0.11µs        ? B/sec</b></font>
nth_prime/StreamingSieve/100000      1.03    134.3±0.83µs        ? B/sec<font color="#859900"><b>    1.00    130.8±0.11µs        ? B/sec</b></font>
nth_prime/StreamingSieve/1000000     1.01  1261.4±53.15µs        ? B/sec<font color="#859900"><b>    1.00   1249.9±3.99µs        ? B/sec</b></font>
prime_pi/Primes/100                  1.01    136.5±1.71µs        ? B/sec<font color="#859900"><b>    1.00    134.9±1.05µs        ? B/sec</b></font>
prime_pi/Primes/10000                1.04    142.5±1.89µs        ? B/sec<font color="#859900"><b>    1.00    137.6±0.52µs        ? B/sec</b></font>
prime_pi/Primes/100000<font color="#859900"><b>               1.00    165.1±1.02µs        ? B/sec</b></font>    1.02    168.7±0.58µs        ? B/sec
prime_pi/Primes/1000000<font color="#859900"><b>              1.00   473.8±10.18µs        ? B/sec</b></font>    1.04    492.9±1.84µs        ? B/sec
prime_pi/Primes/10000000<font color="#859900"><b>             1.00      3.2±0.06ms        ? B/sec</b></font>    1.10      3.5±0.01ms        ? B/sec
prime_pi/Sieve with init/100         1.09     56.9±0.41ns        ? B/sec<font color="#859900"><b>    1.00     52.3±1.09ns        ? B/sec</b></font>
prime_pi/Sieve with init/10000       1.05    234.2±2.27ns        ? B/sec<font color="#859900"><b>    1.00    222.5±2.08ns        ? B/sec</b></font>
prime_pi/Sieve with init/100000      1.01      6.9±0.25µs        ? B/sec<font color="#859900"><b>    1.00      6.9±0.02µs        ? B/sec</b></font>
prime_pi/Sieve with init/1000000<font color="#859900"><b>     1.00    130.2±1.79µs        ? B/sec</b></font>    1.01    131.1±0.29µs        ? B/sec
prime_pi/Sieve with init/10000000<font color="#859900"><b>    1.00    835.2±6.62µs        ? B/sec</b></font>    1.00    836.5±5.56µs        ? B/sec
prime_pi/Sieve/100                   1.08     15.3±0.45ns        ? B/sec<font color="#859900"><b>    1.00     14.1±0.06ns        ? B/sec</b></font>
prime_pi/Sieve/10000                 1.02    102.2±0.53ns        ? B/sec<font color="#859900"><b>    1.00    100.6±0.41ns        ? B/sec</b></font>
prime_pi/Sieve/100000                1.11    351.1±2.29ns        ? B/sec<font color="#859900"><b>    1.00    316.7±1.16ns        ? B/sec</b></font>
prime_pi/Sieve/1000000               1.02    117.6±0.58ns        ? B/sec<font color="#859900"><b>    1.00    115.7±0.42ns        ? B/sec</b></font>
prime_pi/Sieve/10000000              1.11    442.3±2.14ns        ? B/sec<font color="#859900"><b>    1.00   398.2±10.04ns        ? B/sec</b></font>
prime_pi/StreamingSieve/100          1.10    155.5±1.46ns        ? B/sec<font color="#859900"><b>    1.00    142.0±0.50ns        ? B/sec</b></font>
prime_pi/StreamingSieve/10000<font color="#859900"><b>        1.00   1079.8±6.57ns        ? B/sec</b></font>    1.01   1092.9±9.03ns        ? B/sec
prime_pi/StreamingSieve/100000       1.02      6.4±0.04µs        ? B/sec<font color="#859900"><b>    1.00      6.3±0.02µs        ? B/sec</b></font>
prime_pi/StreamingSieve/1000000      1.02    128.7±4.58µs        ? B/sec<font color="#859900"><b>    1.00    125.6±0.12µs        ? B/sec</b></font>
prime_pi/StreamingSieve/10000000     1.02   844.3±16.20µs        ? B/sec<font color="#859900"><b>    1.00    826.4±2.47µs        ? B/sec</b></font>
</pre>
</details>

**Comment by cuviper** [comment]
CI failed in coverage because it can't parse the new lock format:
https://github.com/roblabla/cargo-travis/issues/66

File: primal-sieve/src/sieve.rs [hunk 1]
```diff
@@ -253,21 +253,19 @@ impl Sieve {
 
         let mut ret = Vec::new();
 
-        for p in self.primes_from(0) {
-            let mut count = 0;
-            while n % p == 0 {
+        self.primes_from(0).all(|p| {
```
Comment (huonw) [inline primal-sieve/src/sieve.rs:256]: I personally find the use of `all` for a purely-side-effecting loop like this a bit confusing, but I guess it's linking into the `all` specialisation? Another option that directly expresses the goal would be `try_for_each`, I think? (It seems this was stabilised in 1.27?)

File: primal-sieve/src/streaming/primes.rs [hunk 2]
```diff
@@ -80,18 +77,49 @@ impl Primes {
...
+                self.ones = bits.clone().into_ones();
+                true
+            },
+            None => false,
+        }
+    }
 }
 
+
 impl Iterator for Primes {
```
Comment (huonw) [inline primal-sieve/src/streaming/primes.rs:119]: Given this implementation and `SievePrimes` is almost identical, I'm curious on your thoughts about merging them?

File: primal-sieve/src/sieve.rs (hunk 1 above)
Comment (cuviper) [reply primal-sieve/src/sieve.rs:256]: Yeah, basically we want specialized internal iteration with early termination (`while p*p < n`), which is perfect for `try_fold` or `try_for_each`, except we can't actually specialize those because the `Try` trait itself is still unstable.

This is local code though, so maybe I should invent an inherent method that's clearer, instead of abusing `all`...

File: primal-sieve/src/streaming/primes.rs (hunk 2 above)
Comment (cuviper) [reply primal-sieve/src/streaming/primes.rs:119]: Hmm. The code _is_ almost identical, but they are structurally different enough that they can't just be composed. Maybe an internal helper trait is due here.

File: primal-sieve/src/sieve.rs (hunk 1 above)
Comment (huonw) [reply primal-sieve/src/sieve.rs:256]: Probably not worth it for a single call site, vs. just adding a brief comment like `// use internal iteration` or something?

File: primal-sieve/src/streaming/primes.rs (hunk 2 above)
Comment (huonw) [reply primal-sieve/src/streaming/primes.rs:119]: Maybe worth if/as more methods are specialised, but could be done as eventual follow up work to keep the scope of this smaller (if you're wanting to get it polished off).

File: primal-sieve/src/sieve.rs (hunk 1 above)
Comment (cuviper) [reply primal-sieve/src/sieve.rs]: I realized that my `all` was incorrect, because it didn't bother updating `self.early`, and iterators are allowed to be called again afterward. So I decided to customize it, `for_each_while`.

File: primal-sieve/src/streaming/primes.rs (hunk 2 above)
Comment (cuviper) [reply primal-sieve/src/streaming/primes.rs:119]: I added cross-reference comments as a reminder, but otherwise I think it's OK for now.

**Comment by cuviper** [comment]
@huonw I do appreciate your review, absent or not. :slightly_smiling_face: 

If there are no further comments, I think I'll merge and publish it this afternoon.

**Comment by cuviper** [comment]
err, let's try that with your review reflected, at least.

bors cancel

**Comment by cuviper** [comment]
bors r=huonw

**Comment by cuviper** [comment]
bors r=huonw

**Comment by huonw** [comment]
> If there are no further comments, I think I'll merge and publish it this afternoon.

All good by me 👍

**Comment by cuviper** [comment]
Great, thanks! I'm just working through CI now...

bors r=huonw
